name: Build Xcode project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        name: ["iPhone 16 Pro"]
        os: ["18.2"]
    name: Build Xcode project
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          xcodebuild clean build analyze -scheme ownCloud -project ownCloud.xcodeproj -destination "platform=iOS Simulator,name=${{ matrix.name }},OS=${{ matrix.os }}" | xcpretty && exit ${PIPESTATUS[0]}


