name: CI

on: [push]

jobs:
  test:
    name: Test on destination ${{ matrix.destination }}
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,name=iPhone 8"]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use platform ${{ matrix.destination }}
      run: |
        git submodule update --init
        xcodebuild test -scheme ownCloudTests -destination "${{ matrix.destination }}"
