name: "Update translations"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - master
    
permissions: {}

defaults:
  run:
    shell: pwsh

jobs:
  update-translations:
    permissions:
      contents: write # for git push
    runs-on: ubuntu-latest

    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.ref }}

      - name: l10n-push
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        # we need to use a different docker image for those two, this appears to be a bit tricky with github actions out of the box
        run:  bash .github/workflows/run-in-docker.sh owncloudci/transifex:latest "cd ownCloud/Resources/en.lproj && tx push -s --skip"

      - name: l10n-pull
        run: bash .github/workflows/run-in-docker.sh owncloudci/transifex:latest "cd ownCloud/Resources/ && tx pull --force --skip --all"

      - name: update-repo-before-commit
        run: |
          git status
          git add ownCloud/Resources/*.strings
          git status
          git stash
          git pull --ff-only origin

      - name: commit and push
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          install -d -m 0700 ~/.ssh
          Set-Content -Value "${{ secrets.DEPLOYMENT_SSH_KEY }}" -Path ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          if(git stash list) {
              git stash pop
              install -d -m 0700 ~/.ssh
              Set-Content -Value "${{ secrets.DEPLOYMENT_SSH_KEY }}" -Path ~/.ssh/id_ed25519
              chmod 0600 ~/.ssh/id_ed25519
              git config user.name "ownClouders"
              git config user.email "devops@owncloud.com"
              git add translations/
              git commit -m "[tx] updated client translations from transifex [skip ci]"
              git push git@github.com:owncloud/ios-app.git
          }

  normalize-strings:
    runs-on: macos-13
    name: Normalize .strings file encoding
    needs: update-translations # Ensure this job runs after 'update-translations'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Normalize .strings files to UTF-8
        run: ./normalizestrings.sh
        working-directory: ./tools/normalizestrings/
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Normalized Localizable.strings encoding (UTF-8)
          file_pattern: '*.strings'
