name: "Update translations"

on:
  workflow_dispatch:
  
permissions: {}

defaults:
  run:
    shell: pwsh

jobs:
  update-translations:
    permissions:
      # for git push
      contents: write
    runs-on: ubuntu-latest

    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: "master"

      - name: l10n-remove-old
        run: |
          git checkout ownCloud/Resources/

      - name: l10n-push
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        # we need to use a different docker image for those two, this appears to be a bit tricky with github actions out of the box
        run:  bash .github/workflows/run-in-docker.sh owncloudci/transifex:latest "cd ownCloud/Resources/en.lproj && tx push -s --skip"

      - name: l10n-pull
        run: bash .github/workflows/run-in-docker.sh owncloudci/transifex:latest "cd ownCloud/Resources/ && tx pull --force --skip --all"

      - name: update-repo-before-commit
        run: |
          git status
          git add ownCloud/Resources/*.strings
          git status
          git stash
          git pull --ff-only origin

      - name: commit and push
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          if(git stash list) {
              git stash pop
              install -d -m 0700 ~/.ssh
              Set-Content -Value "${{ secrets.DEPLOYMENT_SSH_KEY }}" -Path ~/.ssh/id_ed25519
              chmod 0600 ~/.ssh/id_ed25519
              git config user.name "ownClouders"
              git config user.email "devops@owncloud.com"
              git add translations/
              git commit -m "[tx] updated client translations from transifex [skip ci]"
              git push git@github.com:owncloud/client.git
            }
